---
version: "3.8"

networks:
  proxy:
    external: true

services:
  website:
      build:
        context: .
        dockerfile: docker/Dockerfile
      image: deowo:latest
      container_name: deowo
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https"
        - "traefik.http.routers.deowo.middlewares=httpsredirect"
        - "traefik.http.routers.deowo.entrypoints=http"
        - "traefik.http.routers.deowosecure.tls=true"
        - "traefik.http.routers.deowosecure.entrypoints=https"
        - "traefik.http.routers.deowosecure.tls.certresolver=http01challenge"
        - "traefik.http.routers.deowo.rule=Host(`deowo.com`, `www.deowo.com`)"
        - "traefik.http.routers.deowosecure.rule=Host(`deowo.com`, `www.deowo.com`)"
      restart: unless-stopped
      networks:
        - proxy
