---
version: "3.7"

networks:
  PROXY_NETWORK:
    external: true

services:
  website:
      build:
        context: .
        dockerfile: docker/Dockerfile
      image: deowo:latest
      container_name: deowo
      # healthcheck:
      #   test: ["CMD", "service", "nginx", "status"]
      #   interval: 30s
      #   timeout: 10s
      #   retries: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https"
        - "traefik.http.routers.deowo.middlewares=httpsredirect"
        - "traefik.http.routers.deowo.entrypoints=http"
        - "traefik.http.routers.deowosecure.tls=true"
        - "traefik.http.routers.deowosecure.entrypoints=https"
        - "traefik.http.routers.deowosecure.tls.certresolver=http01challenge"
        - "traefik.http.routers.deowo.rule=Host(`deowo.com`, `www.deowo.com`)"
        - "traefik.http.routers.deowosecure.rule=Host(`deowo.com`, `www.deowo.com`)"
      restart: always
      networks:
        - PROXY_NETWORK
